name: Docker Assessment Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-assessment:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (Erweiterung für Docker Build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Logge dich in DockerHub ein (wenn nötig)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Baue das Docker-Image für den Calculation-Service
      - name: Build calculation-service image
        run: docker build -t calculation-service ./calculation-service

      # Starte die Docker-Container und führe die Tests aus
      - name: Run containers with docker-compose
        run: docker-compose up -d

      # Test API response
      - name: Test API response
        run: |
          sleep 10
          curl http://localhost:8080/v1/health

      # Shutdown Docker Compose
      - name: Shutdown Docker Compose
        run: docker-compose down
